const db = require('./models/db');
const bcrypt = require('bcryptjs');
const { v4: uuidv4 } = require('uuid');

console.log('🌱 Seeding database...');

// Admin user
const adminId = uuidv4();
const hashedPassword = bcrypt.hashSync('admin123', 10);
db.prepare(`INSERT OR IGNORE INTO users (id, email, password, first_name, last_name, role) VALUES (?, ?, ?, ?, ?, ?)`)
  .run(adminId, 'admin@haddley-cooper.fr', hashedPassword, 'Admin', 'HC', 'admin');

// Test customer
const customerId = uuidv4();
const customerPwd = bcrypt.hashSync('client123', 10);
db.prepare(`INSERT OR IGNORE INTO users (id, email, password, first_name, last_name, role) VALUES (?, ?, ?, ?, ?, ?)`)
  .run(customerId, 'client@test.fr', customerPwd, 'Jean', 'Dupont', 'customer');

// Categories
const categories = [
  { id: uuidv4(), name: 'Hygiène des sols', slug: 'hygiene-sols', description: 'Produits pour nettoyer et entretenir tous types de sols' },
  { id: uuidv4(), name: 'Hygiène des surfaces', slug: 'hygiene-surfaces', description: 'Détergents et désinfectants pour toutes surfaces' },
  { id: uuidv4(), name: 'Hygiène des mains', slug: 'hygiene-mains', description: 'Savons, gels et produits pour l\'hygiène des mains' },
  { id: uuidv4(), name: 'Hygiène des sanitaires', slug: 'hygiene-sanitaires', description: 'Produits spécialisés pour sanitaires' },
  { id: uuidv4(), name: 'Collecte des déchets', slug: 'collecte-dechets', description: 'Sacs poubelle, poubelles et accessoires' },
  { id: uuidv4(), name: 'Univers Piscine', slug: 'univers-piscine', description: 'Produits d\'entretien pour piscines et bassins' },
];

const catStmt = db.prepare(`INSERT OR IGNORE INTO categories (id, name, slug, description) VALUES (?, ?, ?, ?)`);
categories.forEach(c => catStmt.run(c.id, c.name, c.slug, c.description));

const catRows = db.prepare('SELECT id, slug FROM categories').all();
const catMap = Object.fromEntries(catRows.map(c => [c.slug, c.id]));

// ─── PRODUCTS ──────────────────────────────────────────────────────────────
const products = [

  // ══════════════════════════════════════════════
  //  HYGIÈNE DES SOLS  (12 produits)
  // ══════════════════════════════════════════════
  {
    name: 'Lavodor 2D Détergent Surodorant 5L', slug: 'lavodor-2d-5l',
    description: 'Détergent surodorant rémanent pour sols et surfaces. Formule professionnelle concentrée, parfum frais longue durée. Idéal pour les espaces à forte fréquentation.',
    short_description: 'Détergent surodorant concentré 5L',
    price: 18.90, pro_price: 14.50, compare_price: 24.90,
    stock: 150, sku: 'LAV-2D-5L', brand: 'Lavodor', unit: 'bidon 5L',
    is_featured: 1, is_new: 1, category_slug: 'hygiene-sols',
    images: ['https://images.unsplash.com/photo-1585128792020-803d29415281?w=600&h=600&fit=crop&q=80'],
    tags: ['sol', 'surodorant', 'concentré'],
  },
  {
    name: 'Nettoyant Sol Parquet Brillant 1L', slug: 'nettoyant-parquet-1l',
    description: 'Nettoyant spécialement formulé pour parquets vernis, stratifiés et sols en bois. Nettoie en profondeur sans laisser de traces, redonne de l\'éclat et protège la surface.',
    short_description: 'Nettoyant parquet sans traces 1L',
    price: 9.50, pro_price: 7.20, compare_price: 12.90,
    stock: 220, sku: 'NET-PAR-1L', brand: 'Haddley & Cooper', unit: 'flacon 1L',
    is_featured: 0, is_new: 1, category_slug: 'hygiene-sols',
    images: ['https://images.unsplash.com/photo-1563453392212-326cb5df1d57?w=600&h=600&fit=crop&q=80'],
    tags: ['parquet', 'bois', 'brillant'],
  },
  {
    name: 'Dégraissant Sol Cuisine Pro 5L', slug: 'degraissant-sol-cuisine-5l',
    description: 'Dégraissant alcalin concentré haute performance pour sols de cuisines professionnelles. Élimine les graisses les plus tenaces, compatible carrelage et béton.',
    short_description: 'Dégraissant cuisine concentré 5L',
    price: 24.90, pro_price: 18.50, compare_price: 31.00,
    stock: 90, sku: 'DEG-CUI-5L', brand: 'ProClean', unit: 'bidon 5L',
    is_featured: 1, is_new: 0, category_slug: 'hygiene-sols',
    images: ['https://plus.unsplash.com/premium_photo-1684407616442-87bf0d69e8b4?w=600&h=600&fit=crop&q=80'],
    tags: ['dégraissant', 'cuisine', 'professionnel'],
  },
  {
    name: 'Lavette Microfibre Sol 60x80cm x5', slug: 'lavette-microfibre-sol-x5',
    description: 'Lot de 5 lavettes microfibre haute absorption pour sols. Fibres ultrafines qui captent poussières et bactéries sans produit. Lavable jusqu\'à 60°C, réutilisable 500 fois.',
    short_description: 'Lavettes microfibre 60x80 lot de 5',
    price: 14.90, pro_price: 11.00, compare_price: 19.90,
    stock: 180, sku: 'LAV-MIC-60X5', brand: 'Haddley & Cooper', unit: 'lot de 5',
    is_featured: 0, is_new: 0, category_slug: 'hygiene-sols',
    images: ['https://plus.unsplash.com/premium_photo-1681284938563-852a6e4a45e7?w=600&h=600&fit=crop&q=80'],
    tags: ['microfibre', 'lavette', 'réutilisable'],
  },
  {
    name: 'Balai Frange Coton Pro 300g', slug: 'balai-frange-coton-300g',
    description: 'Balai frange en coton pur torsadé, 300g, largeur 60cm. Idéal pour les grands espaces. Compatible avec tous les systèmes de manche fileté standard.',
    short_description: 'Balai frange coton torsadé 300g',
    price: 11.50, pro_price: 8.50, compare_price: 15.00,
    stock: 130, sku: 'BAL-FRA-300', brand: 'ProClean', unit: 'pièce',
    is_featured: 0, is_new: 0, category_slug: 'hygiene-sols',
    images: ['https://images.unsplash.com/photo-1527515637462-cff94ebb57eb?w=600&h=600&fit=crop&q=80'],
    tags: ['balai', 'frange', 'coton'],
  },
  {
    name: 'Manche Aluminium Télescopique 140cm', slug: 'manche-alu-telescopique',
    description: 'Manche télescopique en aluminium anodisé, de 80 à 140cm. Filetage universel, poignée antidérapante, ultra-léger. Compatible balais, raclettes, franges.',
    short_description: 'Manche télescopique alu 80-140cm',
    price: 8.90, pro_price: 6.50, compare_price: 12.00,
    stock: 200, sku: 'MAN-ALU-140', brand: 'ProClean', unit: 'pièce',
    is_featured: 0, is_new: 0, category_slug: 'hygiene-sols',
    images: ['https://images.unsplash.com/photo-1584515933487-779824d29309?w=600&h=600&fit=crop&q=80'],
    tags: ['manche', 'aluminium', 'télescopique'],
  },
  {
    name: 'Raclette Sol Caoutchouc 60cm', slug: 'raclette-sol-60cm',
    description: 'Raclette professionnelle à lame caoutchouc double face 60cm. Idéale pour évacuer l\'eau sur carrelage, béton, résine. Manche vissé non inclus.',
    short_description: 'Raclette caoutchouc professionnel 60cm',
    price: 13.50, pro_price: 9.80, compare_price: 18.00,
    stock: 85, sku: 'RAC-CAO-60', brand: 'ProClean', unit: 'pièce',
    is_featured: 0, is_new: 0, category_slug: 'hygiene-sols',
    images: ['https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&h=600&fit=crop&q=80'],
    tags: ['raclette', 'sol', 'caoutchouc'],
  },
  {
    name: 'Détergent Sols Carrelage Parfum Citron 5L', slug: 'detergent-carrelage-citron-5l',
    description: 'Nettoyant désinfectant pour carrelage et faïence, parfum citron frais. Formule à pH neutre, sans rinçage, éclat garanti. Bidon de 5L avec bouchon doseur.',
    short_description: 'Nettoyant carrelage citron 5L',
    price: 14.90, pro_price: 10.50, compare_price: 19.00,
    stock: 160, sku: 'DET-CAR-CIT5', brand: 'Haddley & Cooper', unit: 'bidon 5L',
    is_featured: 0, is_new: 1, category_slug: 'hygiene-sols',
    images: ['https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&h=600&fit=crop&q=80'],
    tags: ['carrelage', 'citron', 'désinfectant'],
  },
  {
    name: 'Cire Sol PVC & Lino 5L', slug: 'cire-sol-pvc-5l',
    description: 'Cire d\'entretien brillante pour sols PVC, lino et vinyle. Protège, brillante et facile à appliquer. Résistante aux passages intensifs. Bidon 5L professionnel.',
    short_description: 'Cire brillante PVC & lino 5L',
    price: 22.00, pro_price: 16.50, compare_price: 28.00,
    stock: 70, sku: 'CIR-PVC-5L', brand: 'Haddley & Cooper', unit: 'bidon 5L',
    is_featured: 0, is_new: 0, category_slug: 'hygiene-sols',
    images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=600&fit=crop&q=80'],
    tags: ['cire', 'PVC', 'lino'],
  },
  {
    name: 'Décapant Sol Cire & Émulsion 5L', slug: 'decapant-sol-5l',
    description: 'Décapant alcalin puissant pour enlever cires, émulsions et résidus tenaces sur tous types de sols durs. Prépare la surface avant remise en cire.',
    short_description: 'Décapant cires & émulsions 5L',
    price: 19.90, pro_price: 14.00, compare_price: 25.00,
    stock: 55, sku: 'DEC-SOL-5L', brand: 'ProClean', unit: 'bidon 5L',
    is_featured: 0, is_new: 0, category_slug: 'hygiene-sols',
    images: ['https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=600&h=600&fit=crop&q=80'],
    tags: ['décapant', 'cire', 'sol'],
  },
  {
    name: 'Seau Lave-Sol Professionnel 15L', slug: 'seau-lave-sol-15l',
    description: 'Seau professionnel en polypropylène 15L avec presse essoreur et roulettes. Graduation intérieure, bec verseur, poignée ergonomique.',
    short_description: 'Seau avec essoreur 15L sur roulettes',
    price: 34.90, pro_price: 26.00, compare_price: 44.00,
    stock: 40, sku: 'SEA-PRO-15L', brand: 'ProClean', unit: 'pièce',
    is_featured: 1, is_new: 1, category_slug: 'hygiene-sols',
    images: ['https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=600&h=600&fit=crop&q=80'],
    tags: ['seau', 'essoreur', 'professionnel'],
  },
  {
    name: 'Serpillière Microfibre Plate 40cm x3', slug: 'serpilliere-microfibre-plate-x3',
    description: 'Lot de 3 serpillières plates microfibre 40cm pour systèmes de nettoyage à plat. Absorption x7 supérieure au coton, séchage rapide, lavable 60°C.',
    short_description: 'Serpillières plates microfibre 40cm x3',
    price: 17.90, pro_price: 13.00, compare_price: 22.00,
    stock: 110, sku: 'SER-MIC-40X3', brand: 'Haddley & Cooper', unit: 'lot de 3',
    is_featured: 0, is_new: 1, category_slug: 'hygiene-sols',
    images: ['https://images.unsplash.com/photo-1586992953119-9d5d3ebf1da0?w=600&h=600&fit=crop&q=80'],
    tags: ['serpillière', 'microfibre', 'plate'],
  },

  // ══════════════════════════════════════════════
  //  HYGIÈNE DES SURFACES  (12 produits)
  // ══════════════════════════════════════════════
  {
    name: 'ANIOS Surfa\'Safe Premium Spray 750ml', slug: 'anios-surfasafe-750ml',
    description: 'Détergent désinfectant PAE en spray 750ml. Élimine 99,9% des bactéries, virus et levures. Certifié pour usage en milieu médical et alimentaire.',
    short_description: 'Désinfectant surfaces toutes zones',
    price: 7.27, pro_price: 5.80, compare_price: 9.50,
    stock: 320, sku: 'ANI-SSP-750', brand: 'Anios', unit: 'spray 750ml',
    is_featured: 1, is_new: 0, category_slug: 'hygiene-surfaces',
    images: ['https://images.unsplash.com/photo-1639112389900-a858bf671be1?w=600&h=600&fit=crop&q=80'],
    tags: ['désinfectant', 'spray', 'médical'],
  },
  {
    name: 'Nettoyant Désinfectant Multi-Surfaces 1L', slug: 'nettoyant-multi-surfaces-1l',
    description: 'Nettoyant désinfectant polyvalent pour toutes surfaces dures. Action rapide en 5 minutes, senteur fraîche. Compatible inox, verre, plastique et mélaminé.',
    short_description: 'Désinfectant multi-surfaces 1L',
    price: 6.90, pro_price: 4.90, compare_price: 8.90,
    stock: 410, sku: 'NET-MUL-1L', brand: 'Haddley & Cooper', unit: 'flacon 1L',
    is_featured: 0, is_new: 1, category_slug: 'hygiene-surfaces',
    images: ['https://images.unsplash.com/photo-1586992953119-9d5d3ebf1da0?w=600&h=600&fit=crop&q=80'],
    tags: ['multi-surfaces', 'désinfectant', 'polyvalent'],
  },
  {
    name: 'Lingettes Désinfectantes Citron x72', slug: 'lingettes-desinfectantes-x72',
    description: 'Boîte de 72 lingettes désinfectantes imprégnées. Élimine 99,9% des germes. Idéales pour les surfaces fréquemment touchées : claviers, téléphones, poignées.',
    short_description: 'Lingettes désinfectantes x72 citron',
    price: 5.49, pro_price: 3.90, compare_price: 7.20,
    stock: 550, sku: 'LIN-DES-72C', brand: 'CleanMax', unit: 'boîte 72 lingettes',
    is_featured: 0, is_new: 0, category_slug: 'hygiene-surfaces',
    images: ['https://plus.unsplash.com/premium_photo-1661591285003-9abbde56bf8a?w=600&h=600&fit=crop&q=80'],
    tags: ['lingettes', 'citron', 'pratique'],
  },
  {
    name: 'Produit Vitres & Miroirs Professionnel 1L', slug: 'produit-vitres-1l',
    description: 'Nettoyant vitres à base d\'alcool pour une brillance irréprochable. Sans traces, sèche instantanément. Qualité cristal pour vitres, miroirs et surfaces vitrées.',
    short_description: 'Nettoyant vitres sans traces 1L',
    price: 5.90, pro_price: 4.20, compare_price: 7.50,
    stock: 290, sku: 'VIT-PRO-1L', brand: 'ProClean', unit: 'flacon 1L',
    is_featured: 0, is_new: 0, category_slug: 'hygiene-surfaces',
    images: ['https://plus.unsplash.com/premium_photo-1676810459906-b269db9bd6e7?w=600&h=600&fit=crop&q=80'],
    tags: ['vitres', 'miroirs', 'sans traces'],
  },
  {
    name: '3M Post-it Traçabilité Alimentaire 6 blocs', slug: '3m-postit-tracabilite',
    description: 'Lot de 6 blocs de 50 feuilles Post-it pour la traçabilité alimentaire. Adhésif soluble dans l\'eau, ne laisse aucun résidu. Idéal pour restauration et industrie agroalimentaire.',
    short_description: 'Post-it traçabilité alimentaire x6',
    price: 31.42, pro_price: 24.00, compare_price: 38.00,
    stock: 200, sku: '3M-PTI-6B', brand: '3M', unit: 'lot de 6 blocs',
    is_featured: 1, is_new: 1, category_slug: 'hygiene-surfaces',
    images: ['https://plus.unsplash.com/premium_photo-1706191097326-cd317671d1fb?w=600&h=600&fit=crop&q=80'],
    tags: ['traçabilité', 'alimentaire', '3M'],
  },
  {
    name: 'Désinfectant Surfaces Alimentaires 5L', slug: 'desinfectant-alimentaire-5l',
    description: 'Désinfectant sans rinçage pour surfaces en contact avec les aliments. Certifié EN 1276. Idéal cuisines professionnelles, hôtellerie et restauration.',
    short_description: 'Désinfectant alimentaire sans rinçage 5L',
    price: 29.90, pro_price: 22.00, compare_price: 36.00,
    stock: 75, sku: 'DES-ALI-5L', brand: 'Anios', unit: 'bidon 5L',
    is_featured: 1, is_new: 0, category_slug: 'hygiene-surfaces',
    images: ['https://images.unsplash.com/photo-1584515933487-779824d29309?w=600&h=600&fit=crop&q=80'],
    tags: ['alimentaire', 'sans rinçage', 'cuisine pro'],
  },
  {
    name: 'Crème à Récurer Inox & Émaillé 750ml', slug: 'creme-recurer-inox-750ml',
    description: 'Crème récurante douce pour inox, émail, céramique et chrome. Nettoie et fait briller sans rayer. Élimine calcaire, traces et dépôts alimentaires.',
    short_description: 'Crème récurante inox & émail 750ml',
    price: 4.90, pro_price: 3.50, compare_price: 6.50,
    stock: 380, sku: 'CRE-REC-750', brand: 'Haddley & Cooper', unit: 'flacon 750ml',
    is_featured: 0, is_new: 0, category_slug: 'hygiene-surfaces',
    images: ['https://images.unsplash.com/photo-1583947582886-f40ec95dd752?w=600&h=600&fit=crop&q=80'],
    tags: ['inox', 'récurant', 'brillant'],
  },
  {
    name: 'Spray Nettoyant Inox Pro 500ml', slug: 'spray-inox-500ml',
    description: 'Spray spécial inox élimine traces de doigts, eau calcaire et taches grasses. Laisse un film protecteur anti-traces. Résultats visibles dès la première utilisation.',
    short_description: 'Nettoyant inox anti-traces 500ml',
    price: 6.20, pro_price: 4.50, compare_price: 8.00,
    stock: 250, sku: 'SPR-INX-500', brand: 'ProClean', unit: 'spray 500ml',
    is_featured: 0, is_new: 1, category_slug: 'hygiene-surfaces',
    images: ['https://images.unsplash.com/photo-1639112389900-a858bf671be1?w=600&h=600&fit=crop&q=80'],
    tags: ['inox', 'spray', 'anti-traces'],
  },
  {
    name: 'Chiffon Microfibre Multicolore x10', slug: 'chiffon-microfibre-x10',
    description: 'Lot de 10 chiffons microfibre 40x40cm code couleur (jaune, rouge, bleu, vert). Idéal pour éviter les contaminations croisées. Lavable à 90°C.',
    short_description: 'Chiffons microfibre code couleur x10',
    price: 12.90, pro_price: 9.00, compare_price: 16.00,
    stock: 300, sku: 'CHI-MIC-COL10', brand: 'Haddley & Cooper', unit: 'lot de 10',
    is_featured: 0, is_new: 0, category_slug: 'hygiene-surfaces',
    images: ['https://plus.unsplash.com/premium_photo-1684407616442-87bf0d69e8b4?w=600&h=600&fit=crop&q=80'],
    tags: ['chiffon', 'microfibre', 'code couleur'],
  },
  {
    name: 'Spray Désinfectant Air & Surfaces 400ml', slug: 'spray-air-surfaces-400ml',
    description: 'Désinfectant biocide pour l\'air et les surfaces. Élimine les odeurs et neutralise les bactéries en suspension. Parfum pin frais. 400ml ≈ 600 pulvérisations.',
    short_description: 'Désinfectant air & surfaces 400ml',
    price: 5.90, pro_price: 4.00, compare_price: 7.50,
    stock: 420, sku: 'SPR-AIR-400', brand: 'FreshPro', unit: 'aérosol 400ml',
    is_featured: 0, is_new: 1, category_slug: 'hygiene-surfaces',
    images: ['https://plus.unsplash.com/premium_photo-1670445044667-3c24bd5330b4?w=600&h=600&fit=crop&q=80'],
    tags: ['air', 'désinfectant', 'odeurs'],
  },
  {
    name: 'Éponge Grattante Double Face x10', slug: 'eponge-grattante-x10',
    description: 'Lot de 10 éponges double face : côté doux pour surfaces délicates, côté grattant pour incrustations tenaces. Longue durée de vie, ne raye pas.',
    short_description: 'Éponges double face x10',
    price: 7.90, pro_price: 5.50, compare_price: 10.00,
    stock: 500, sku: 'EPO-GRA-10', brand: 'CleanMax', unit: 'lot de 10',
    is_featured: 0, is_new: 0, category_slug: 'hygiene-surfaces',
    images: ['https://images.unsplash.com/photo-1563453392212-326cb5df1d57?w=600&h=600&fit=crop&q=80'],
    tags: ['éponge', 'grattante', 'cuisine'],
  },
  {
    name: 'Nettoyant Dégraissant Universel Concentré 5L', slug: 'degraissant-universel-5l',
    description: 'Dégraissant toutes surfaces ultra-concentré, dilution jusqu\'à 1/50. Élimine graisses, huiles et souillures organiques sur tout support. Économique et écologique.',
    short_description: 'Dégraissant universel concentré 5L',
    price: 27.90, pro_price: 20.00, compare_price: 34.00,
    stock: 90, sku: 'DEG-UNI-5L', brand: 'ProClean', unit: 'bidon 5L',
    is_featured: 1, is_new: 0, category_slug: 'hygiene-surfaces',
    images: ['https://images.unsplash.com/photo-1584744982491-665216d95f8b?w=600&h=600&fit=crop&q=80'],
    tags: ['dégraissant', 'concentré', 'universel'],
  },

  // ══════════════════════════════════════════════
  //  HYGIÈNE DES MAINS  (10 produits)
  // ══════════════════════════════════════════════
  {
    name: 'Gel Hydroalcoolique 500ml Pompe', slug: 'gel-hydro-500ml',
    description: 'Gel hydroalcoolique à 70% d\'alcool. Action bactéricide, virucide et fongicide. Formule douce avec aloe vera. Séchage rapide sans rinçage.',
    short_description: 'Gel hydro 70% alcool avec pompe',
    price: 4.99, pro_price: 3.50, compare_price: 6.99,
    stock: 500, sku: 'GEL-HA-500P', brand: 'Haddley & Cooper', unit: 'flacon 500ml',
    is_featured: 0, is_new: 1, category_slug: 'hygiene-mains',
    images: ['https://images.unsplash.com/photo-1583947582886-f40ec95dd752?w=600&h=600&fit=crop&q=80'],
    tags: ['gel', 'hydroalcoolique', 'mains'],
  },
  {
    name: 'Gel Hydroalcoolique 5L Recharge', slug: 'gel-hydro-5l',
    description: 'Bidon de 5L de gel hydroalcoolique pour rechargement de distributeurs. 70% alcool, formule enrichie en glycérine pour ne pas dessécher les mains.',
    short_description: 'Gel hydro 70% alcool recharge 5L',
    price: 28.90, pro_price: 21.00, compare_price: 35.00,
    stock: 120, sku: 'GEL-HA-5LR', brand: 'Haddley & Cooper', unit: 'bidon 5L',
    is_featured: 1, is_new: 0, category_slug: 'hygiene-mains',
    images: ['https://plus.unsplash.com/premium_photo-1661591285003-9abbde56bf8a?w=600&h=600&fit=crop&q=80'],
    tags: ['gel', 'hydroalcoolique', 'recharge'],
  },
  {
    name: 'Savon Liquide Mains Doux 5L', slug: 'savon-liquide-mains-5l',
    description: 'Savon liquide doux pour les mains en bidon de 5L. Ph neutre, enrichi en glycérine, idéal pour une utilisation fréquente. Compatible tous distributeurs. Parfum fleurs blanches.',
    short_description: 'Savon liquide mains 5L recharge',
    price: 12.50, pro_price: 9.00, compare_price: 16.90,
    stock: 380, sku: 'SAV-LIQ-5L', brand: 'Haddley & Cooper', unit: 'bidon 5L',
    is_featured: 1, is_new: 0, category_slug: 'hygiene-mains',
    images: ['https://plus.unsplash.com/premium_photo-1679064286720-9f28c0f012d8?w=600&h=600&fit=crop&q=80'],
    tags: ['savon', 'mains', 'recharge'],
  },
  {
    name: 'Savon Liquide Mains Antibactérien 1L', slug: 'savon-antibacterien-1l',
    description: 'Savon liquide antibactérien en flacon pompe 1L. Élimine 99,9% des bactéries. Formule douce adaptée aux lavages fréquents. Parfum citron frais.',
    short_description: 'Savon antibactérien pompe 1L citron',
    price: 5.90, pro_price: 4.20, compare_price: 7.90,
    stock: 420, sku: 'SAV-ABT-1L', brand: 'CleanMax', unit: 'flacon 1L',
    is_featured: 0, is_new: 1, category_slug: 'hygiene-mains',
    images: ['https://images.unsplash.com/photo-1645567455251-334ed4702f9b?w=600&h=600&fit=crop&q=80'],
    tags: ['savon', 'antibactérien', 'citron'],
  },
  {
    name: 'Distributeur Savon Mural Inox 1L', slug: 'distributeur-savon-mural',
    description: 'Distributeur de savon liquide en inox brossé, capacité 1L. Fixation murale, idéal vestiaires, toilettes et cuisines. Pompe à levier robuste, rechargeable facilement.',
    short_description: 'Distributeur inox 1L fixation murale',
    price: 28.90, pro_price: 22.00, compare_price: 36.00,
    stock: 75, sku: 'DIS-SAV-INX', brand: 'ProClean', unit: 'pièce',
    is_featured: 0, is_new: 1, category_slug: 'hygiene-mains',
    images: ['https://images.unsplash.com/photo-1645567455251-334ed4702f9b?w=600&h=600&fit=crop&q=80'],
    tags: ['distributeur', 'inox', 'mural'],
  },
  {
    name: 'Distributeur Gel Hydro Automatique 1L', slug: 'distributeur-gel-auto-1l',
    description: 'Distributeur automatique sans contact pour gel hydroalcoolique, capacité 1L. Capteur infrarouge, alimentation piles ou secteur. Idéal accueils, halls et restaurants.',
    short_description: 'Distributeur gel auto sans contact 1L',
    price: 45.00, pro_price: 34.00, compare_price: 58.00,
    stock: 35, sku: 'DIS-GEL-AUTO', brand: 'ProClean', unit: 'pièce',
    is_featured: 1, is_new: 1, category_slug: 'hygiene-mains',
    images: ['https://images.unsplash.com/photo-1583947582886-f40ec95dd752?w=600&h=600&fit=crop&q=80'],
    tags: ['distributeur', 'automatique', 'sans contact'],
  },
  {
    name: 'Crème Mains Hydratante 500ml Pompe', slug: 'creme-mains-500ml',
    description: 'Crème hydratante mains intensive en format professionnel 500ml avec pompe. Formule non grasse, absorption rapide. Idéale après lavages répétés.',
    short_description: 'Crème hydratante mains 500ml pompe',
    price: 8.90, pro_price: 6.50, compare_price: 11.90,
    stock: 200, sku: 'CRE-MAI-500', brand: 'Haddley & Cooper', unit: 'flacon 500ml',
    is_featured: 0, is_new: 0, category_slug: 'hygiene-mains',
    images: ['https://plus.unsplash.com/premium_photo-1679064286720-9f28c0f012d8?w=600&h=600&fit=crop&q=80'],
    tags: ['crème', 'mains', 'hydratant'],
  },
  {
    name: 'Brosse Ongles Chirurgicale x10', slug: 'brosse-ongles-x10',
    description: 'Lot de 10 brosses à ongles chirurgicales stériles à usage unique. Double face, poils nylon doux. Conforme aux exigences d\'hygiène alimentaire et médicale.',
    short_description: 'Brosses ongles chirurgicales x10',
    price: 6.90, pro_price: 4.80, compare_price: 9.00,
    stock: 600, sku: 'BRO-ONG-10', brand: 'CleanMax', unit: 'lot de 10',
    is_featured: 0, is_new: 0, category_slug: 'hygiene-mains',
    images: ['https://plus.unsplash.com/premium_photo-1661591285003-9abbde56bf8a?w=600&h=600&fit=crop&q=80'],
    tags: ['brosse', 'ongles', 'chirurgicale'],
  },
  {
    name: 'Essuie-mains Papier Zigzag Blanc x3000', slug: 'essuie-mains-zigzag-x3000',
    description: 'Carton de 3000 feuilles essuie-mains papier en Z blanc 2 plis. Format 24x21cm. Compatible distributeurs universels. Absorbant et doux pour la peau.',
    short_description: 'Essuie-mains papier Z blanc 3000 feuilles',
    price: 18.90, pro_price: 13.50, compare_price: 24.00,
    stock: 250, sku: 'ESS-ZIG-3000', brand: 'Haddley & Cooper', unit: 'carton 3000 feuilles',
    is_featured: 0, is_new: 0, category_slug: 'hygiene-mains',
    images: ['https://images.unsplash.com/photo-1584515933487-779824d29309?w=600&h=600&fit=crop&q=80'],
    tags: ['essuie-mains', 'papier', 'zigzag'],
  },
  {
    name: 'Gants Nitrile Bleus Taille M x100', slug: 'gants-nitrile-bleus-m-x100',
    description: 'Boîte de 100 gants nitrile non poudrés bleus taille M. Résistants aux produits chimiques, sans latex. Idéaux pour l\'entretien, la restauration et les soins.',
    short_description: 'Gants nitrile bleus M x100',
    price: 9.90, pro_price: 7.00, compare_price: 13.00,
    stock: 800, sku: 'GAN-NIT-BM100', brand: 'CleanMax', unit: 'boîte 100 gants',
    is_featured: 1, is_new: 0, category_slug: 'hygiene-mains',
    images: ['https://plus.unsplash.com/premium_photo-1684407616442-87bf0d69e8b4?w=600&h=600&fit=crop&q=80'],
    tags: ['gants', 'nitrile', 'bleus'],
  },

  // ══════════════════════════════════════════════
  //  HYGIÈNE DES SANITAIRES  (10 produits)
  // ══════════════════════════════════════════════
  {
    name: 'Détartrant WC Professionnel 750ml', slug: 'detartrant-wc-750ml',
    description: 'Détartrant WC acide concentré à action gel épaissie. Adhère aux parois, élimine le calcaire, les dépôts et les taches jaunes. Parfum pin frais. Action en 5 minutes.',
    short_description: 'Détartrant WC gel concentré 750ml',
    price: 4.20, pro_price: 2.90, compare_price: 5.50,
    stock: 460, sku: 'DET-WC-750', brand: 'Haddley & Cooper', unit: 'flacon 750ml',
    is_featured: 0, is_new: 0, category_slug: 'hygiene-sanitaires',
    images: ['https://plus.unsplash.com/premium_photo-1664372899354-99e6d9f50f58?w=600&h=600&fit=crop&q=80'],
    tags: ['WC', 'détartrant', 'sanitaire'],
  },
  {
    name: 'Spray Désodorisant Sanitaires 400ml', slug: 'desodorisant-sanitaires-400ml',
    description: 'Spray désodorisant pour sanitaires et cabinets d\'aisance. Neutralise les mauvaises odeurs instantanément. Diffuse un parfum frais longue durée. 400ml ≈ 600 pulvérisations.',
    short_description: 'Désodorisant sanitaires 400ml spray',
    price: 3.90, pro_price: 2.70, compare_price: 5.20,
    stock: 620, sku: 'DES-SAN-400', brand: 'FreshPro', unit: 'aérosol 400ml',
    is_featured: 0, is_new: 1, category_slug: 'hygiene-sanitaires',
    images: ['https://plus.unsplash.com/premium_photo-1670445044667-3c24bd5330b4?w=600&h=600&fit=crop&q=80'],
    tags: ['désodorisant', 'sanitaires', 'spray'],
  },
  {
    name: 'Nettoyant Surpuissant Robinets & Douches 500ml', slug: 'nettoyant-robinets-500ml',
    description: 'Anti-calcaire spécial robinetterie, douches et baignoires. Gel à action prolongée, détartre et fait briller l\'inox et le chrome. Sans rayures, résultats visibles dès la première utilisation.',
    short_description: 'Anti-calcaire robinets & douches 500ml',
    price: 6.50, pro_price: 4.50, compare_price: 8.90,
    stock: 310, sku: 'NET-ROB-500', brand: 'ProClean', unit: 'flacon 500ml',
    is_featured: 1, is_new: 0, category_slug: 'hygiene-sanitaires',
    images: ['https://images.unsplash.com/photo-1773177930292-463ca3c5b86a?w=600&h=600&fit=crop&q=80'],
    tags: ['calcaire', 'robinets', 'chrome'],
  },
  {
    name: 'Pastilles WC Nettoyantes x50', slug: 'pastilles-wc-x50',
    description: 'Boîte de 50 pastilles nettoyantes et désodorisantes pour réservoir WC. Action longue durée, formule anti-calcaire et anti-tartre. Teinte bleu eau.',
    short_description: 'Pastilles WC nettoyantes x50',
    price: 8.50, pro_price: 6.00, compare_price: 11.00,
    stock: 350, sku: 'PAS-WC-50', brand: 'CleanMax', unit: 'boîte 50 pastilles',
    is_featured: 0, is_new: 0, category_slug: 'hygiene-sanitaires',
    images: ['https://plus.unsplash.com/premium_photo-1664372899354-99e6d9f50f58?w=600&h=600&fit=crop&q=80'],
    tags: ['pastilles', 'WC', 'réservoir'],
  },
  {
    name: 'Gel WC Ultra-Puissant 750ml Citron', slug: 'gel-wc-citron-750ml',
    description: 'Gel épais nettoyant WC au citron. Formule acide qui élimine calcaire et urine incrustée. Action prolongée sur les parois verticales. Flacon ergonomique coudé.',
    short_description: 'Gel WC citron épais 750ml',
    price: 3.80, pro_price: 2.60, compare_price: 5.00,
    stock: 520, sku: 'GEL-WC-CIT750', brand: 'Haddley & Cooper', unit: 'flacon 750ml',
    is_featured: 0, is_new: 1, category_slug: 'hygiene-sanitaires',
    images: ['https://plus.unsplash.com/premium_photo-1670445044667-3c24bd5330b4?w=600&h=600&fit=crop&q=80'],
    tags: ['gel', 'WC', 'citron'],
  },
  {
    name: 'Brosse WC Ergonomique avec Support', slug: 'brosse-wc-ergonomique',
    description: 'Brosse WC à tête inclinée avec support de rangement. Poils en nylon résistant aux produits chimiques. Design compact, couvercle fermé pour une hygiène optimale.',
    short_description: 'Brosse WC + support hygiénique',
    price: 12.90, pro_price: 9.00, compare_price: 16.00,
    stock: 150, sku: 'BRO-WC-ERG', brand: 'ProClean', unit: 'pièce + support',
    is_featured: 0, is_new: 0, category_slug: 'hygiene-sanitaires',
    images: ['https://plus.unsplash.com/premium_photo-1664372899354-99e6d9f50f58?w=600&h=600&fit=crop&q=80'],
    tags: ['brosse', 'WC', 'support'],
  },
  {
    name: 'Détartrant Sanitaires Acide 5L', slug: 'detartrant-sanitaires-5l',
    description: 'Détartrant acide concentré pour sanitaires collectifs. Élimine calcaire, rouille et dépôts minéraux. Compatible céramique, acier inox, émail. Bidon 5L professionnel.',
    short_description: 'Détartrant acide sanitaires 5L',
    price: 19.90, pro_price: 14.50, compare_price: 25.00,
    stock: 80, sku: 'DET-SAN-5L', brand: 'ProClean', unit: 'bidon 5L',
    is_featured: 1, is_new: 0, category_slug: 'hygiene-sanitaires',
    images: ['https://plus.unsplash.com/premium_photo-1664372899354-99e6d9f50f58?w=600&h=600&fit=crop&q=80'],
    tags: ['détartrant', 'acide', 'collectif'],
  },
  {
    name: 'Nettoyant Carrelage Salle de Bain 1L', slug: 'nettoyant-salle-de-bain-1l',
    description: 'Nettoyant spécial salle de bain qui élimine les dépôts de calcaire, traces de savon et moisissures. Parfum frais. Compatible carrelage, joints et paroi de douche.',
    short_description: 'Nettoyant salle de bain anti-calcaire 1L',
    price: 5.20, pro_price: 3.70, compare_price: 7.00,
    stock: 340, sku: 'NET-SDB-1L', brand: 'Haddley & Cooper', unit: 'flacon 1L',
    is_featured: 0, is_new: 1, category_slug: 'hygiene-sanitaires',
    images: ['https://images.unsplash.com/photo-1773177930292-463ca3c5b86a?w=600&h=600&fit=crop&q=80'],
    tags: ['salle de bain', 'calcaire', 'moisissures'],
  },
  {
    name: 'Anti-Moisissures Spray 500ml', slug: 'anti-moisissures-500ml',
    description: 'Traitement anti-moisissures puissant pour joints de douche, salle de bain et sous-sol. Elimine et prévient la formation de moisissures. Formule à base de chlore.',
    short_description: 'Anti-moisissures spray chloré 500ml',
    price: 7.90, pro_price: 5.50, compare_price: 10.00,
    stock: 260, sku: 'ANT-MOI-500', brand: 'ProClean', unit: 'spray 500ml',
    is_featured: 0, is_new: 0, category_slug: 'hygiene-sanitaires',
    images: ['https://plus.unsplash.com/premium_photo-1670445044667-3c24bd5330b4?w=600&h=600&fit=crop&q=80'],
    tags: ['moisissures', 'joints', 'douche'],
  },
  {
    name: 'Bloc WC Désodorisant Lavande x6', slug: 'bloc-wc-lavande-x6',
    description: 'Lot de 6 blocs WC désodorisants à la lavande, avec crochet de fixation. Dure jusqu\'à 4 semaines. Formule anti-calcaire intégrée, préserve la cuvette.',
    short_description: 'Blocs WC lavande avec crochet x6',
    price: 6.50, pro_price: 4.50, compare_price: 8.50,
    stock: 480, sku: 'BLO-WC-LAV6', brand: 'FreshPro', unit: 'lot de 6',
    is_featured: 0, is_new: 0, category_slug: 'hygiene-sanitaires',
    images: ['https://plus.unsplash.com/premium_photo-1664372899354-99e6d9f50f58?w=600&h=600&fit=crop&q=80'],
    tags: ['bloc WC', 'lavande', 'désodorisant'],
  },

  // ══════════════════════════════════════════════
  //  COLLECTE DES DÉCHETS  (9 produits)
  // ══════════════════════════════════════════════
  {
    name: 'Sacs Poubelle 110L Noir x50', slug: 'sacs-poubelle-110l',
    description: 'Sacs poubelle haute résistance 110 litres en polyéthylène recyclé. Résistants aux déchirures et perforations. Lot de 50 sacs.',
    short_description: 'Sacs poubelle 110L résistants x50',
    price: 12.90, pro_price: 9.50, compare_price: 16.90,
    stock: 400, sku: 'SAC-110-N50', brand: 'Haddley & Cooper', unit: 'rouleau 50 sacs',
    is_featured: 0, is_new: 0, category_slug: 'collecte-dechets',
    images: ['https://images.unsplash.com/photo-1602262442764-c14f8db98045?w=600&h=600&fit=crop&q=80'],
    tags: ['sacs', 'poubelle', 'recyclé'],
  },
  {
    name: 'Sacs Poubelle 30L Blanc x100', slug: 'sacs-poubelle-30l-blanc',
    description: 'Sacs poubelle 30L blanc opaque, idéals pour corbeilles de bureau et petites poubelles. Résistants, format standard. Lot de 100 sacs en rouleau.',
    short_description: 'Sacs poubelle 30L blanc x100',
    price: 8.90, pro_price: 6.20, compare_price: 11.50,
    stock: 700, sku: 'SAC-30-B100', brand: 'Haddley & Cooper', unit: 'rouleau 100 sacs',
    is_featured: 0, is_new: 0, category_slug: 'collecte-dechets',
    images: ['https://images.unsplash.com/photo-1606037150583-fb842a55bae7?w=600&h=600&fit=crop&q=80'],
    tags: ['sacs', '30L', 'bureau'],
  },
  {
    name: 'Sacs Poubelle 50L Transparent x100', slug: 'sacs-poubelle-50l-transparent',
    description: 'Sacs poubelle transparents 50L, format intermédiaire idéal bureaux et collectivités. Permet le contrôle visuel du contenu. Lot de 100 sacs économique.',
    short_description: 'Sacs poubelle 50L transparent x100',
    price: 10.90, pro_price: 7.80, compare_price: 14.00,
    stock: 550, sku: 'SAC-50-T100', brand: 'Haddley & Cooper', unit: 'rouleau 100 sacs',
    is_featured: 0, is_new: 1, category_slug: 'collecte-dechets',
    images: ['https://images.unsplash.com/photo-1602262442764-c14f8db98045?w=600&h=600&fit=crop&q=80'],
    tags: ['sacs', '50L', 'transparent'],
  },
  {
    name: 'Poubelle à Pédale Inox 60L', slug: 'poubelle-pedale-inox-60l',
    description: 'Poubelle à pédale en inox brossé capacité 60L. Couvercle à ouverture douce et silencieuse, seau intérieur amovible. Idéale cuisine professionnelle ou bureau.',
    short_description: 'Poubelle pédale inox 60L avec seau',
    price: 59.90, pro_price: 45.00, compare_price: 75.00,
    stock: 35, sku: 'POB-INX-60L', brand: 'ProClean', unit: 'pièce',
    is_featured: 1, is_new: 1, category_slug: 'collecte-dechets',
    images: ['https://plus.unsplash.com/premium_photo-1664189121552-f6d1dbf2a45c?w=600&h=600&fit=crop&q=80'],
    tags: ['poubelle', 'inox', 'pédale'],
  },
  {
    name: 'Poubelle Tri Sélectif 3x10L', slug: 'poubelle-tri-selectif-3x10l',
    description: 'Station de tri sélectif 3 compartiments de 10L. Code couleur intégré (jaune, bleu, vert). Couvercle amovible, pieds antidérapants. Parfaite pour bureaux et espaces communs.',
    short_description: 'Station tri sélectif 3x10L code couleur',
    price: 49.90, pro_price: 37.00, compare_price: 62.00,
    stock: 25, sku: 'POB-TRI-3X10', brand: 'ProClean', unit: 'pièce',
    is_featured: 1, is_new: 1, category_slug: 'collecte-dechets',
    images: ['https://plus.unsplash.com/premium_photo-1664189121552-f6d1dbf2a45c?w=600&h=600&fit=crop&q=80'],
    tags: ['tri sélectif', 'recyclage', 'bureau'],
  },
  {
    name: 'Corbeille à Papier Métal 14L', slug: 'corbeille-papier-metal-14l',
    description: 'Corbeille à papier en métal ajouré 14L. Finition époxy blanc. Légère et robuste, idéale pour tous les bureaux et espaces de travail.',
    short_description: 'Corbeille métal ajourée 14L blanc',
    price: 9.90, pro_price: 7.00, compare_price: 13.00,
    stock: 180, sku: 'COR-PAP-MET14', brand: 'Haddley & Cooper', unit: 'pièce',
    is_featured: 0, is_new: 0, category_slug: 'collecte-dechets',
    images: ['https://plus.unsplash.com/premium_photo-1664189121552-f6d1dbf2a45c?w=600&h=600&fit=crop&q=80'],
    tags: ['corbeille', 'bureau', 'métal'],
  },
  {
    name: 'Sacs Déchets Verts 150L x25', slug: 'sacs-dechets-verts-150l',
    description: 'Sacs très haute résistance 150L pour déchets de jardin, gravats légers et déchets encombrants. Traitement UV, poignées renforcées. Lot de 25.',
    short_description: 'Sacs très résistants déchets 150L x25',
    price: 14.90, pro_price: 10.50, compare_price: 19.00,
    stock: 280, sku: 'SAC-150-V25', brand: 'Haddley & Cooper', unit: 'lot de 25',
    is_featured: 0, is_new: 0, category_slug: 'collecte-dechets',
    images: ['https://images.unsplash.com/photo-1606037150583-fb842a55bae7?w=600&h=600&fit=crop&q=80'],
    tags: ['sacs', '150L', 'jardin'],
  },
  {
    name: 'Sacs Hygiéniques Lingettes & Protections x200', slug: 'sacs-hygieniques-x200',
    description: 'Sachets hygiéniques opaque pour poubelles de salle de bain et sanitaires. Idéaux lingettes, protections et déchets sanitaires. Format 15x18cm, lot de 200.',
    short_description: 'Sachets hygiéniques sanitaires x200',
    price: 7.90, pro_price: 5.50, compare_price: 10.00,
    stock: 600, sku: 'SAC-HYG-200', brand: 'CleanMax', unit: 'lot de 200',
    is_featured: 0, is_new: 0, category_slug: 'collecte-dechets',
    images: ['https://images.unsplash.com/photo-1606037150583-fb842a55bae7?w=600&h=600&fit=crop&q=80'],
    tags: ['sachets', 'hygiéniques', 'sanitaires'],
  },
  {
    name: 'Cendrier de Sol Professionnel Noir', slug: 'cendrier-sol-professionnel',
    description: 'Cendrier sur pied en acier laqué noir mat, hauteur 90cm. Sable intégré anti-combustion, seau amovible facile à vider. Idéal entrées d\'immeubles et espaces fumeurs.',
    short_description: 'Cendrier sur pied acier noir 90cm',
    price: 39.90, pro_price: 29.00, compare_price: 50.00,
    stock: 30, sku: 'CEN-SOL-PRO', brand: 'ProClean', unit: 'pièce',
    is_featured: 0, is_new: 0, category_slug: 'collecte-dechets',
    images: ['https://plus.unsplash.com/premium_photo-1664189121552-f6d1dbf2a45c?w=600&h=600&fit=crop&q=80'],
    tags: ['cendrier', 'fumeurs', 'acier'],
  },

  // ══════════════════════════════════════════════
  //  UNIVERS PISCINE  (9 produits)
  // ══════════════════════════════════════════════
  {
    name: 'Détartrant Bassin Purissimeau 5L', slug: 'detartrant-bassin-5l',
    description: 'Détartrant spécial bassins, filtres et électrodes. Formule acide concentrée pour éliminer le calcaire et les dépôts minéraux. Compatible liner et parois.',
    short_description: 'Détartrant piscine concentré 5L',
    price: 22.50, pro_price: 17.00, compare_price: 28.00,
    stock: 80, sku: 'DET-PUR-5L', brand: 'Purissimeau', unit: 'bidon 5L',
    is_featured: 1, is_new: 0, category_slug: 'univers-piscine',
    images: ['https://plus.unsplash.com/premium_photo-1672308016665-699aefbc5f40?w=600&h=600&fit=crop&q=80'],
    tags: ['piscine', 'détartrant', 'bassin'],
  },
  {
    name: 'Chlore Choc Granulés Piscine 1kg', slug: 'chlore-choc-1kg',
    description: 'Chlore choc en granulés à dissolution rapide pour traitement choc ou entretien régulier. Élimine algues, bactéries et micro-organismes. Teneur en chlore actif 56%. 1kg.',
    short_description: 'Chlore choc granulés 56% actif 1kg',
    price: 14.90, pro_price: 10.50, compare_price: 19.90,
    stock: 130, sku: 'CHL-CHC-1KG', brand: 'Purissimeau', unit: 'seau 1kg',
    is_featured: 1, is_new: 0, category_slug: 'univers-piscine',
    images: ['https://images.unsplash.com/photo-1558617320-e695f0d420de?w=600&h=600&fit=crop&q=80'],
    tags: ['chlore', 'choc', 'algues'],
  },
  {
    name: 'Régulateur pH+ Piscine 1kg', slug: 'regulateur-ph-plus-1kg',
    description: 'Correcteur de pH à la hausse en granulés pour piscine. Augmente le pH de l\'eau pour maintenir la plage idéale (7,2 – 7,6). Action rapide.',
    short_description: 'Régulateur pH+ granulés piscine 1kg',
    price: 11.90, pro_price: 8.20, compare_price: 15.50,
    stock: 110, sku: 'PH-PLUS-1KG', brand: 'Purissimeau', unit: 'seau 1kg',
    is_featured: 0, is_new: 1, category_slug: 'univers-piscine',
    images: ['https://plus.unsplash.com/premium_photo-1680646213100-29bfeca6d475?w=600&h=600&fit=crop&q=80'],
    tags: ['pH', 'piscine', 'correcteur'],
  },
  {
    name: 'Régulateur pH- Piscine 1kg', slug: 'regulateur-ph-moins-1kg',
    description: 'Correcteur de pH à la baisse en granulés. Abaisse le pH quand celui-ci est trop élevé. Dosage précis, action rapide sans troubler l\'eau.',
    short_description: 'Régulateur pH- granulés piscine 1kg',
    price: 10.90, pro_price: 7.80, compare_price: 14.00,
    stock: 100, sku: 'PH-MOIN-1KG', brand: 'Purissimeau', unit: 'seau 1kg',
    is_featured: 0, is_new: 0, category_slug: 'univers-piscine',
    images: ['https://plus.unsplash.com/premium_photo-1680646213100-29bfeca6d475?w=600&h=600&fit=crop&q=80'],
    tags: ['pH', 'piscine', 'baisse'],
  },
  {
    name: 'Algicide Piscine Liquide 5L', slug: 'algicide-piscine-5l',
    description: 'Algicide préventif et curatif en bidon de 5L. Empêche et élimine toutes les formes d\'algues vertes, noires et mousse. Compatibles toutes membranes.',
    short_description: 'Algicide préventif & curatif piscine 5L',
    price: 24.90, pro_price: 18.00, compare_price: 31.00,
    stock: 70, sku: 'ALG-LIQ-5L', brand: 'Purissimeau', unit: 'bidon 5L',
    is_featured: 1, is_new: 0, category_slug: 'univers-piscine',
    images: ['https://images.unsplash.com/photo-1558617320-e695f0d420de?w=600&h=600&fit=crop&q=80'],
    tags: ['algicide', 'algues', 'piscine'],
  },
  {
    name: 'Floculant Liquide Piscine 1L', slug: 'floculant-piscine-1l',
    description: 'Floculant liquide pour clarifier une eau trouble. Regroupe les fines particules en suspension pour un filtrage efficace. Compatible filtres sable et cartouche.',
    short_description: 'Floculant clarificateur eau piscine 1L',
    price: 9.90, pro_price: 7.00, compare_price: 13.00,
    stock: 120, sku: 'FLO-LIQ-1L', brand: 'Purissimeau', unit: 'flacon 1L',
    is_featured: 0, is_new: 1, category_slug: 'univers-piscine',
    images: ['https://plus.unsplash.com/premium_photo-1672308016665-699aefbc5f40?w=600&h=600&fit=crop&q=80'],
    tags: ['floculant', 'eau trouble', 'clarifiant'],
  },
  {
    name: 'Chlore Lent Galets 250g x5kg', slug: 'chlore-lent-galets-5kg',
    description: 'Seau de 5kg de galets de chlore lent 200g à dissolution progressive. Maintien du taux de chlore en continu. Idéal pour skimmer ou diffuseur flottant.',
    short_description: 'Galets chlore lent 200g piscine 5kg',
    price: 39.90, pro_price: 29.00, compare_price: 49.00,
    stock: 60, sku: 'CHL-LEN-5KG', brand: 'Purissimeau', unit: 'seau 5kg',
    is_featured: 1, is_new: 0, category_slug: 'univers-piscine',
    images: ['https://images.unsplash.com/photo-1558617320-e695f0d420de?w=600&h=600&fit=crop&q=80'],
    tags: ['chlore', 'galets', 'lent'],
  },
  {
    name: 'Kit Analyse Eau Piscine 4 en 1', slug: 'kit-analyse-piscine',
    description: 'Kit d\'analyse de l\'eau pour piscine : mesure pH, chlore libre, alcalinité (TAC) et dureté (TH). 100 tests inclus. Résultats rapides par comparateur colorimétrique.',
    short_description: 'Kit analyse pH + chlore + TAC + TH x100',
    price: 16.90, pro_price: 12.00, compare_price: 22.00,
    stock: 90, sku: 'KIT-ANA-4EN1', brand: 'Purissimeau', unit: 'kit 100 tests',
    is_featured: 0, is_new: 1, category_slug: 'univers-piscine',
    images: ['https://plus.unsplash.com/premium_photo-1680646213100-29bfeca6d475?w=600&h=600&fit=crop&q=80'],
    tags: ['kit analyse', 'pH', 'chlore'],
  },
  {
    name: 'Épuisette Piscine Fine Maille 45cm', slug: 'epuisette-piscine-45cm',
    description: 'Épuisette à fine maille pour ramasser feuilles, insectes et petits débris en surface. Cadre aluminium 45cm, filet nylon renforcé, compatible manches fileté standard.',
    short_description: 'Épuisette fine maille piscine 45cm',
    price: 18.90, pro_price: 13.50, compare_price: 24.00,
    stock: 55, sku: 'EPI-FIN-45', brand: 'Purissimeau', unit: 'pièce',
    is_featured: 0, is_new: 0, category_slug: 'univers-piscine',
    images: ['https://plus.unsplash.com/premium_photo-1672308016665-699aefbc5f40?w=600&h=600&fit=crop&q=80'],
    tags: ['épuisette', 'piscine', 'nettoyage'],
  },
];

const prodStmt = db.prepare(`
  INSERT OR IGNORE INTO products
  (id, name, slug, description, short_description, price, pro_price, compare_price, stock, sku, brand, unit, category_id, is_featured, is_new, images, tags)
  VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`);

products.forEach(p => {
  prodStmt.run(
    uuidv4(), p.name, p.slug, p.description, p.short_description,
    p.price, p.pro_price, p.compare_price, p.stock, p.sku, p.brand, p.unit,
    catMap[p.category_slug] || null, p.is_featured ? 1 : 0, p.is_new ? 1 : 0,
    JSON.stringify(p.images), JSON.stringify(p.tags)
  );
});

// Sample order
const order1Id = uuidv4();
db.prepare(`INSERT OR IGNORE INTO orders (id, order_number, user_id, status, payment_status, subtotal, shipping_cost, total, shipping_address)
  VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`)
  .run(order1Id, 'HC-2024-0001', customerId, 'delivered', 'paid', 26.17, 4.90, 31.07,
    JSON.stringify({ street: '12 rue de la Paix', city: 'Paris', postal_code: '75001', country: 'France' }));

console.log(`✅ Database seeded — ${products.length} produits, 6 catégories`);
console.log('👤 Admin: admin@haddley-cooper.fr / admin123');
console.log('👤 Client: client@test.fr / client123');
